### ISSUE TITLE
请求学习

### ISSUE THREAD

**Issue by HelloWord1996** [stdnull/RunMap#1]
本人想学习了解RunMap的从设计到开发的全过程，如果不介意的话可不可以仔细描述一下它的数据库、流程图等，如果介意的话，那就算了，谢谢！

**Comment by skyinu** [comment]
数据库创建在LocationDataBase.java,操作放在DataManager.java...至于流程图我没画过,你可以看代码...如果有兴趣...

**Comment by skyinu** [comment]
@HelloWord1996 数据库创建在LocationDataBase.java,操作放在DataManager.java...至于流程图我没画过,你可以看代码...如果有兴趣...
